apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-demo
  template:
    metadata:
      labels:
        app: aks-demo
    spec:
      containers:
      - name: aks-demo-app
        image: jubbuseacrinmh.azurecr.io/aks-demo-app:$(Build.BuildId)
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aks-demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: aks-demo
